// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9cZqVduWvqf9jorUJsm3-7tJC7kCbF6s',
    appId: '1:898458171079:web:a3f0477ca7c89c3df370e2',
    messagingSenderId: '898458171079',
    projectId: 'carrentalapp-dbfb2',
    authDomain: 'carrentalapp-dbfb2.firebaseapp.com',
    storageBucket: 'carrentalapp-dbfb2.appspot.com',
    measurementId: 'G-ZP5FW35VKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1hUBbx5_W0Rg1LpZsaiBBwX8oZ9_d9Ew',
    appId: '1:898458171079:android:a5e41f1b2c75a88cf370e2',
    messagingSenderId: '898458171079',
    projectId: 'carrentalapp-dbfb2',
    storageBucket: 'carrentalapp-dbfb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJx3p35S198mIiKwV9Oz-kS7fmHRxfL2Y',
    appId: '1:898458171079:ios:6a205e71f205855cf370e2',
    messagingSenderId: '898458171079',
    projectId: 'carrentalapp-dbfb2',
    storageBucket: 'carrentalapp-dbfb2.appspot.com',
    iosBundleId: 'com.example.finalMobile',
  );
}
